application: gymm3mo
version: 3
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /js
  static_dir: js
- url: /manifest
  static_dir: manifest
  mime_type: text/cache-manifest
- url: /.*
  script: gymmemo.py